### ISSUE TITLE
cffi library 'libgdf.so' has no function, constant or global variable named 'gdf_left_join_generic'

### ISSUE THREAD

**Issue by a-ghorbani** [mapd/mapd-ml-demo#10]
Apparently there is a version conflict in `pygdf`/`ibgdf_cffi`
Just importing `pygdf` in Jupyter notebook throws the following error:
```bash
AttributeError: cffi library 'libgdf.so' has no function, constant or global variable named 'gdf_left_join_generic'
```

**Comment by wamsiv** [comment]
Looks like a cache issue with labels, should be fixed in #11
